apiVersion: v1
kind: Service
metadata:
  name: mldep
  namespace: kube-public
spec:
  type: LoadBalancer
  selector:
    app: mldep
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000